version: '3.8'
services:
  database:
    container_name: database
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: "time_deal"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    container_name: login_session_redis
    image: redis:latest
    ports:
      - "6379:6379"
